### ISSUE TITLE
General clean-up

### ISSUE THREAD

**Issue by mcbouslog** [mcbouslog/usa_wildlifewatch_teampage#3]
There's probably a lot that can be removed or edited from template due to this particular project's small scope. I know the ReadMe should be updated at minimum, are there other clean-up tasks I could do?

**Comment by srallen** [comment]
@mcbouslog, you could probably remove the `.editorconfig` and the npm test script. Also, there's still a .DS_Store in the src folder on github.

**Comment by srallen** [comment]
also the postcss stuff in the package.json and in the gulp file can be removed. We're not using those and I think you forked this before we removed that stuff completely.

**Comment by mcbouslog** [comment]
Sounds good, I think I've made all the changes noted above. I need to update the ReadMe and package.json file to reflect this specific project and not the starterify though?  I'm not sure how-/if I should reference the starterify project this project is based on, but based on Chimp-Zoo and Plankton looks like just clear things out and keep it simple?
